version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: dnz_postgres
    restart: always
    environment:
      POSTGRES_USER: dnz_user
      POSTGRES_PASSWORD: dnz_password
      POSTGRES_DB: dnz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
